language: python
python:
  - '2.7'
before_install:
    #  - sudo apt-get update
    #  - sudo apt-get install python-pip
install: sudo apt-get install python-numpy
script: py.test -v
notifications:
  email:
    recipients:
      - seiya.ono12@gmail.com
    on_success: change
    on_failure: always
